### ISSUE TITLE
Piecharts?

### ISSUE THREAD

**Issue by Hipster74** [pablofrommars/GGNet#3]
Hi, any Roadmap for piecharts?

**Comment by pablofrommars** [comment]
Hi,

Piecharts are barplots in polar coordinates and will be implemented that way. It's not as simple as just creating a new geom.

This [article](https://www.data-to-viz.com/caveat/pie.html) explains some of the caveats associated with piecharts and provides alternatives ;)

I personally avoid them but if enough people request it, I can consider having a stab at it.

Thanks for your interest.

**Comment by pablofrommars** [comment]
If you really need them, you can probably implement them using/abusing geom_map. Your data source would contain the coordinates of the boundaries of each sector. I reckon it's kinda hacky but should work with minimal effort.

Let me know if you need assistance.

**Comment by Hipster74** [comment]
Ok, I’m new to GGNet so the solution with hacking geom_map is a bit above my head unfortunately. 

Maybe the quick fix is to use a component like ChartJs.Blazor for the pie chart ( I’m reproducing an older report with some pie charts so I have to stick to them for now).

**Comment by jan-ai** [comment]
> This article explains some of the caveats associated with piecharts and provides alternatives ;)

Even I can agree with some of the arguments, why pie charts might not be the best choice for everything. At the same time I see no difference between an single column stacked bar chart and a donut chart, as both are the same in terms of data and representation. The only difference is the coordination system they are using. This leads us to ggplot2, where there is a coord_polar() function, which can be used to have donut-charts. Obviously it would be good idea to have the same thing implemented here as ggplot2 was the inspiration, but as far as I can see this seems rather complicated when using svg. Even the "bearing" option of svg doesn’t look too promising, but might be something to have a second look at. 

Have you already thought about the bearing option or a Geom_Donut function?

Would be nice to have something like this here:
[Donut chart](https://community-cdn.rstudio.com/uploads/default/original/2X/c/cd05ce076d0403c9e32a49235b280136e692c5c3.jpeg)

**Comment by pablofrommars** [comment]
@jan-ai Thanks for your feedback! The difference would be that humans tend to better compare by lengths than by angles. A single stacked column is indeed bad practice, a "regular" bar chart with descending/ascending observation is probably clearer in most cases.

I have never used the bearing commands but will look into it. I have however played a bit with [the elliptical arc curve commands](https://www.w3.org/TR/svg-paths/#PathDataEllipticalArcCommands) and would seem like a good tool for polar coordinates.

As stated before, support for circular graphics will only be done after arbitrary coordinate systems are supported. Any other way will just feel wrong :)

What I am open to do thought is expending the capability of geom_map from polygons to more advance path commands, say relative the center of the panel for example.

**Comment by jan-ai** [comment]
After having a deeper look into the code, I believe the only thing to do is adding a new geom class "Donut" using a path shape or extending class "Bar" allowing the usage of a path shape instead of only rectangle (let's say translating rectangle to a path). The class Area already handles path shapes, but the usage of svg arc command (A instead of L only) has to be added. Even “dodge” and “stack” could be implemented without efforts using the radius of the arc as a y position, while “flip” is out of my imagine. The X position (or in case of stack the summed X position) is just translated into the arc angle. What do you believe? Do you want give a try or should I? Or do you still believe that geom_map is the way to go, which is currently out of my understanding, but seems to be extra effort for everyone who wants to use the stuff.

I also still think of using polar coords as a translation in class Area. If the class Bar is generally using a path (instead of an rectangle) the points could be just translated into a polar coord "in/before" class Area and instead of using a line (svg L command) an arc (svg A command) could be used when polar coords are active.

**Comment by pablofrommars** [comment]
Geom_map extension is what I will be working on, and maybe a helper library for data manipulation. I don’t want to “patch” the base source specifically for pie charts. Generalised coordinate systems support has higher priority on my roadmap.

**Comment by pablofrommars** [comment]
Here is a nice lightweight component library for users interested in pie charts for Blazor https://www.webassemblyman.com/blazor/blazorpiechart.html

**Comment by jan-ai** [comment]
I've upgraded GGNet to support coordinates systems. First version currently supports cartesian, flipped cartesian and polar coordinates. While polar coordinates do not support all shapes, rectangles used by bar charts are support and gives you pie or donuts charts (depending on the setup of the plot)

See latest version at https://github.com/jan-ai/GGNet. The demo includes 1 pie and 1 donut chart.

PS: There is a breaking change regarding flip option used before, which is not supported anymore. It has to be replaced by Coord_Flip (see demo)

![image](https://user-images.githubusercontent.com/52295393/103013648-ca0b6c80-453d-11eb-9370-50da64656f97.png)

![image](https://user-images.githubusercontent.com/52295393/103013693-d8f21f00-453d-11eb-9124-44d3d98b65db.png)

**Comment by pablofrommars** [comment]
Looks good!
